### ISSUE TITLE
3D bbox estimation gives bad results

### ISSUE THREAD

**Issue by modraa-pixels** [m-parchami/3DVehicleDetection#1]
Hello,

I trained the model following the notebook but when I test it to generate 3D boxes from 2D labels it gives bad results. It either generates Boxes that are far from the object or with too big dimensions for the target object.
These are examples of results I got knowing that I change average dimensions corresponding to the target object!
One other thing, when running the notebook I found out that coordinates for the 2D bounding box were inversed so I changed (it gave more close result but still not accurate at all) 
![téléchargement (1)](https://user-images.githubusercontent.com/58752885/144453266-b97c0db5-5c62-4ad0-be22-420a0ce5ad0b.png)
![téléchargement](https://user-images.githubusercontent.com/58752885/144453275-6f8d803a-586c-4444-b21f-0859151db44c.png)

**Comment by m-parchami** [comment]
Hi Mohamed,
Thank you for trying out this repo and reporting the issue.
Unfortunately, I am a bit busy because of my travel. I will look into it and let you know. It is probably a minor issue in pre-process and post-processing of the data. From what I see now, the angles seem to be right, but the translation vector is off. I guess after fixing the T vector, the size will be fine (because of the perspective effect). So the issue is probably in the translation vector computation. I will try to find out the exact issue and fix it this week. 
Best.

**Comment by m-parchami** [comment]
Really sorry for such a late reply.

I tried the entire code again, and couldn't see any issues. I trained the model from scratch and used Fast-RCNN for initial 2D boxes (marked by option 3 in the notebook). 

If you or anyone else comes across any issues in the future, please do not hesitate to open up an issue here. I try my best to respond much faster this time :)
